name: Deploy to Skynet

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn build
          env:
            REACT_APP_MORALIS_ID: ${{ secrets.REACT_APP_MORALIS_ID }}
            REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}


      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}